
// User
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const UPDATE_USER_STORE = 'UPDATE_USER_STORE';
export const LOADING_USER = 'LOADING_USER';

export const UPDATE_COLLEAGUE_STORE = 'UPDATE_COLLEAGUE_STORE';
export const INITIAL_COLLEAGUE_STORE = 'INITIAL_COLLEAGUE_STORE';

// Chat
export const UPDATE_CHAT_STORE = 'UPDATE_CHAT_STORE';
export const INITIAL_CHAT_STORE = 'INITIAL_CHAT_STORE';

// UI
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

//Posts
export const UPDATE_POST_STORE = 'UPDATE_POST_STORE';
export const INITIAL_POST_STORE = 'INITIAL_POST_STORE';
export const SET_SCREAM = 'SET_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const POST_SCREAM = 'POST_SCREAM';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

// advertise
export const UPDATE_ADVERTISE_STORE = 'UPDATE_ADVERTISE_STORE';


//base
export const UPDATE_BASE_STORE = 'UPDATE_BASE_STORE';
export const INITIAL_BASE_STORE = 'INITIAL_BASE_STORE';
